# Generated by Django 4.1.2 on 2023-01-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.DateTimeField(auto_now_add=True)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('numero', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('direccion_pedido', models.CharField(default='', max_length=100)),
                ('estado_pedido', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Asignado'), (5, 'Enviado'), (6, 'No Entregado'), (7, 'Entregado'), (8, 'Completado')], default=1)),
                ('fecha_actualizado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
