# Generated by Django 4.1.2 on 2022-11-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0003_alter_pedidos_estado_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='estado_pedido',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Asignado'), (5, 'Enviado'), (7, 'No Entregado'), (6, 'Entregado'), (10, 'Completado')], default=1, verbose_name='status'),
        ),
    ]
