# Generated by Django 4.1.2 on 2023-01-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_usuarios_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='reset_password',
            field=models.IntegerField(choices=[(1, 'Activado'), (2, 'Desactivado')], default=2),
        ),
    ]
